mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cherbini.faceattendance.model
spring:
  redis:
    #redis数据库索引
    database: 0
    #redis服务器host
    host: localhost
    #redis端口号
    port: 6379
    #redis密码，默认为空
    password: redispassword
    #连接redis超时时间（毫秒）
    time-out: 0ms
    #jedis连接池

    jedis:
      pool:
        #最大等待时间
        max-wait: 1000ms
        #最大连接数量
        max-active: 1000
        #最大空闲数量
        max-idle: 10
        #最小空闲数量
        min-idle: 1

  thymeleaf:
    mode: HTML5
    cache: false
# 定位模板的目录
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/faceattendance?useUnicode=true&characterEncoding=utf-8
server:
  port: 80
